# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0041_auto_20160822_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='fedora_created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création sur Fedora'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fedora_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de modification sur Fedora'),
        ),
        migrations.AlterField(
            model_name='article',
            name='oai_datestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Datestamp OAI'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='fedora_created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création sur Fedora'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='fedora_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de modification sur Fedora'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='oai_datestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Datestamp OAI'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='fedora_created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création sur Fedora'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='fedora_updated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de modification sur Fedora'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='oai_datestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Datestamp OAI'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='oai_datestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Datestamp OAI'),
        ),
    ]
