# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import erudit.fedora.modelmixins


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0042_auto_20160822_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création sur Fedora')),
                ('fedora_updated', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de modification sur Fedora')),
                ('code', models.SlugField(help_text='Code', max_length=255, unique=True, verbose_name='Code')),
                ('localidentifier', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Identifiant unique')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('subname', models.CharField(blank=True, max_length=400, null=True, verbose_name='Nom complet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('first_publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Première année de publication')),
                ('last_publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dernière année de publication')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_units', to='erudit.Collection', verbose_name='Collection')),
            ],
            options={
                'verbose_name': 'Unité de recherche',
                'verbose_name_plural': 'Unités de recherche',
                'ordering': ('name',),
            },
            bases=(erudit.fedora.modelmixins.FedoraMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SearchUnitCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création sur Fedora')),
                ('fedora_updated', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de modification sur Fedora')),
                ('localidentifier', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Identifiant unique')),
                ('title', models.CharField(max_length=400, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('search_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='erudit.SearchUnit', verbose_name='Unité de recherche')),
            ],
            options={
                'verbose_name': "Collection d'unité de recherche",
                'verbose_name_plural': "Collections d'unités de recherche",
                'ordering': ('title',),
            },
            bases=(erudit.fedora.modelmixins.FedoraMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SearchUnitDocument',
            fields=[
                ('eruditdocument_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erudit.EruditDocument')),
                ('fedora_created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création sur Fedora')),
                ('fedora_updated', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de modification sur Fedora')),
                ('title', models.CharField(max_length=400, verbose_name='Titre')),
                ('abstract', models.TextField(verbose_name='Résumé')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Année de publication')),
                ('description_url', models.URLField(blank=True, null=True, verbose_name='URL vers la description')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISSN')),
                ('isbn_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISSN numérique')),
                ('authors', models.ManyToManyField(to='erudit.Author', verbose_name='Auteurs')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='erudit.SearchUnitCollection', verbose_name='Collection')),
            ],
            options={
                'verbose_name': "Document d'unité de recherche",
                'verbose_name_plural': "Documents d'unités de recherche",
                'ordering': ('title',),
            },
            bases=('erudit.eruditdocument', erudit.fedora.modelmixins.FedoraMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SearchUnitDocumentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_created', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de création sur Fedora')),
                ('fedora_updated', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Date de modification sur Fedora')),
                ('file', models.FileField(upload_to='search_unit_attachments', verbose_name='Fichier')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='erudit.SearchUnitDocument', verbose_name='Document')),
            ],
            options={
                'verbose_name_plural': "Fichiers de documents d'unités de recherche",
                'verbose_name': "Fichier de document d'une unité de recherche",
            },
            bases=(erudit.fedora.modelmixins.FedoraMixin, models.Model),
        ),
    ]
