# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0043_searchunit_searchunitcollection_searchunitdocument_searchunitdocumentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchunit',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
    ]
