# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-23 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0044_searchunit_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchunit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='search_unit_logos', verbose_name='Logo'),
        ),
    ]
