# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erudit', '0045_searchunit_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchunitdocument',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erudit.Publisher', verbose_name='Éditeur'),
        ),
    ]
